all:
	g++ -std=c++0x -O2 -Wno-write-strings main.cpp Camera.cpp GL.cpp mat4.cpp Overall.cpp ShaderProgram.cpp Texture.cpp uvec3.cpp vec2.cpp vec3.cpp vec4.cpp -lGLEW -lGLU -lGL -lglut -lSOIL -o ../bin/grass 
